### ISSUE TITLE
Can't connect to Binance

### ISSUE THREAD

**Issue by andremvilela** [CoinAlpha/hummingbot-docs#230] opened 2021-02-15 04:05 UTC
Hello guys, 
 
 I followed every step on https://hummingbot.io/academy/quickstart/run-bot/ but, unfortunately, the bot never runs. I can check my balance and run paper mode. But I can't make real transactions since it doesn't connect to Binance. I tried Hummingbot on Windows and Mac with no luck. Paper mode works like a charm, though.

 Does anyone knows how to fix this?

<img width="1512" alt="Captura de Tela 2021-02-15 às 00 43 52" src="https://user-images.githubusercontent.com/79070640/107903227-6db63f00-6f27-11eb-84de-4a18c4b4d316.png">

Thanks!

**Comment by RC-13** [comment] 2021-02-15 04:18
Hello @andremvilela, try running the `connect` command and make sure that your Binance key is marked as YES for both `Key Added` and `Key Confirmed`. If both are okay, run the `status` command to check if the bot pick ups the current market price (the best bid price, best ask price, and mid-price) and just indicate that there are `no active maker order` similar to this image:
![image](https://user-images.githubusercontent.com/57189990/107904617-498a4a80-6f87-11eb-9980-ef7d46380524.png)

If that's the case, and you have sufficient balance, make sure that your `order_amount` meets the exchange minimum order size requirement (Binance minimum is around $10-$11) or set your order amount higher than the required minimum order size. In case you need additional help, get in touch with us on our [Discord server](https://discord.hummingbot.io/) for faster support.

**Comment by andremvilela** [comment] 2021-02-16 01:57
Hello! Thanks for your reply. Yes, that was the issue. I was aware of that, but I couldn't imagine that would prevent me from logging into the API (you know, at first you get kinda scared of doing something wrong configuring HummingBot).

Thanks again and have a nice one!

**Comment by RC-13** [comment] 2021-02-16 02:18
Great! I'm glad that the cause has been identified, feel free to reach us again if you need additional help. I will now close this ticket.

**Closed by RC-13** 2021-02-16 02:18 UTC
